// montanaCountyTaxRates.js
const montanaCountyTaxRates = {
  MT: {
    default: 0.0, // Montana has no state sales tax
    counties: {
      Beaverhead: 0.0,
      'Big Horn': 0.0,
      Blaine: 0.0,
      Broadwater: 0.0,
      Carbon: 0.0,
      Carter: 0.0,
      Cascade: 0.0,
      Chouteau: 0.0,
      Custer: 0.0,
      Daniels: 0.0,
      Dawson: 0.0,
      'Deer Lodge': 0.0,
      Fallon: 0.0,
      Fergus: 0.0,
      Flathead: 0.0,
      Gallatin: 0.0,
      Garfield: 0.0,
      Glacier: 0.0,
      'Golden Valley': 0.0,
      Granite: 0.0,
      Hill: 0.0,
      Jefferson: 0.0,
      'Judith Basin': 0.0,
      Lake: 0.0,
      'Lewis and Clark': 0.0,
      Liberty: 0.0,
      Lincoln: 0.0,
      McCone: 0.0,
      Madison: 0.0,
      Meagher: 0.0,
      Mineral: 0.0,
      Missoula: 0.0,
      Musselshell: 0.0,
      Park: 0.0,
      Petroleum: 0.0,
      Phillips: 0.0,
      Pondera: 0.0,
      'Powder River': 0.0,
      Powell: 0.0,
      Prairie: 0.0,
      Ravalli: 0.0,
      Richland: 0.0,
      Roosevelt: 0.0,
      Rosebud: 0.0,
      Sanders: 0.0,
      Sheridan: 0.0,
      'Silver Bow': 0.0,
      Stillwater: 0.0,
      'Sweet Grass': 0.0,
      Teton: 0.0,
      Toole: 0.0,
      Treasure: 0.0,
      Valley: 0.0,
      Wheatland: 0.0,
      Wibaux: 0.0,
      Yellowstone: 0.0,
    },
  },
};

module.exports = montanaCountyTaxRates;
