// pennsylvaniaCountyTaxRates.js
const pennsylvaniaCountyTaxRates = {
  PA: {
    default: 0.06, // State base rate
    counties: {
      Adams: 0.0,
      Allegheny: 0.01, // Total 7.00%
      Armstrong: 0.0,
      Beaver: 0.0,
      Bedford: 0.0,
      Berks: 0.0,
      Blair: 0.0,
      Bradford: 0.0,
      Bucks: 0.0,
      Butler: 0.0,
      Cambria: 0.0,
      Cameron: 0.0,
      Carbon: 0.0,
      Centre: 0.0,
      Chester: 0.0,
      Clarion: 0.0,
      Clearfield: 0.0,
      Clinton: 0.0,
      Columbia: 0.0,
      Crawford: 0.0,
      Cumberland: 0.0,
      Dauphin: 0.0,
      Delaware: 0.0,
      Elk: 0.0,
      Erie: 0.0,
      Fayette: 0.0,
      Forest: 0.0,
      Franklin: 0.0,
      Fulton: 0.0,
      Greene: 0.0,
      Huntingdon: 0.0,
      Indiana: 0.0,
      Jefferson: 0.0,
      Juniata: 0.0,
      Lackawanna: 0.0,
      Lancaster: 0.0,
      Lawrence: 0.0,
      Lebanon: 0.0,
      Lehigh: 0.0,
      Luzerne: 0.0,
      Lycoming: 0.0,
      McKean: 0.0,
      Monroe: 0.0,
      Montgomery: 0.0,
      Montour: 0.0,
      Northampton: 0.0,
      Northumberland: 0.0,
      Perry: 0.0,
      Philadelphia: 0.02, // Total 8.00%
      Pike: 0.0,
      Potter: 0.0,
      Schuylkill: 0.0,
      Snyder: 0.0,
      Somerset: 0.0,
      Sullivan: 0.0,
      Susquehanna: 0.0,
      Tioga: 0.0,
      Union: 0.0,
      Venango: 0.0,
      Warren: 0.0,
      Washington: 0.0,
      Wayne: 0.0,
      Westmoreland: 0.0,
      Wyoming: 0.0,
      York: 0.0,
    },
  },
};

module.exports = pennsylvaniaCountyTaxRates;
